collections:
  skippers:
    output: true

defaults:
  - scope:
      path: ""
      type: "skippers"
    values:
      layout: "skipper"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"