baseurl: "/pyraegea"
permalink: /:categories/:title/

collections:
  yachts:
    output: true

defaults:
  - scope:
      path: ""
      type: "yachts"
    values:
      layout: "yacht"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"