version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --baseurl /
    volumes:
      - .:/srv/jekyll
      - bundle_data:/usr/local/bundle
    ports:
      - 4000:4000
    environment:
      JEKYLL_ENV: development

volumes:
  bundle_data:
